export {
  Kernel,
  SYSTEM_ISSUER,
  type SimSystem,
  type TickContext,
  type TickResult,
  type CommandHandler,
  type AccessGuard,
  type GuardedAccess,
  type SystemTelemetry,
  type KernelOptions,
} from './kernel.js';
export {
  World,
  Query,
  Component,
  SoAComponent,
  ObjectComponent,
  type FieldType,
  type SoASchema,
  type SoAViews,
  type SoAInit,
  type SystemAccess,
  type ObjectView,
  type ObjectMutView,
  type EntityInspection,
} from './ecs.js';
export { EventBus } from './eventBus.js';
export { TickDriver, BASE_TICKS_PER_SECOND, REAL_SECONDS_PER_DAY, type Speed, type DriverOptions } from './driver.js';
export {
  CalendarSystem,
  calendarFromTick,
  TICKS_PER_DAY,
  DAYS_PER_SEASON,
  SEASONS_PER_YEAR,
  TICKS_PER_SEASON,
  TICKS_PER_YEAR,
  SEASON_NAMES,
  type CalendarDate,
  type SeasonName,
  type DayStartedData,
  type SeasonStartedData,
  type YearStartedData,
} from './time.js';
export {
  recordReplay,
  verifyReplay,
  type ReplayScenario,
  type ReplayRecord,
  type ScheduledCommand,
  type HashSample,
  type VerifyResult,
} from './harness.js';
export {
  SaveManager,
  kernelSection,
  worldSection,
  reconcileModManifest,
  modReconciliationHasFindings,
  SAVE_FORMAT_VERSION,
  type SaveSection,
  type CampaignSave,
  type CampaignSaveHeader,
  type Migration,
  type ModReconciliationReport,
  type SandboxFlags,
} from './persistence.js';
export type { KernelSaveState } from './kernel.js';
export type { WorldSaveState, ComponentSaveState, EncodedObjectValue } from './ecs.js';
export { generateWorld, worldHash } from './worldgen/pipeline.js';
export { classifyTile, tileVariant, fillDepressions } from './worldgen/stages.js';
export { hash01, valueNoise, fbm } from './worldgen/noise.js';
export {
  Biome,
  BIOME_COUNT,
  BIOME_NAMES,
  RiverMark,
  MAP_TILES,
  DEFAULT_PARAMS,
  type BiomeId,
  type MapSize,
  type LandmassStyle,
  type WorldGenParams,
  type WorldLayers,
  type WorldDef,
  type RiverPath,
  type WorldGenStage,
  type ProgressFn,
} from './worldgen/types.js';
export { guaranteeStartResources, startHarvesterRequirements, type HarvesterRequirement } from './worldgen/resourceGuarantee.js';
export {
  registerVillageGameplay,
  defineVillageComponents,
  constructionSystem,
  VillageOps,
  VILLAGE_RADIUS_T1,
  VILLAGE_MIN_SPACING,
  CENTER_DEF_ID,
  type VillageGameplay,
  type VillageComponents,
  type TerrainAccessor,
  type PlacementVerdict,
} from './game/villages.js';
export {
  registerPopulationGameplay,
  FOOD_PER_PERSON_DAY,
  FORAGE_FLOOR,
  BIRTH_RATE,
  FAMINE_MORTALITY,
  JOY_NEUTRAL,
  JOY_MIGRATION_RATE,
  HAPPINESS_FOOD_WEIGHT,
  HAPPINESS_SHELTER_WEIGHT,
  SERVICE_JOY_CAP,
  HAPPINESS_DRIFT_TARGET,
  joyContributions,
  joyTarget,
  joyFertility,
  joyMigration,
  type JoyBreakdown,
  type PopulationGameplay,
  type PopulationComponent,
  type StartingPopulation,
} from './game/population.js';
export { BUILDERS_PER_SITE, type VillageSettings } from './game/villages.js';
export {
  registerEconomyGameplay,
  ResourceLedger,
  BASE_STORAGE,
  KEEP_FOOD_BUFFER,
  OUTBOX_DAYS,
  type EconomyGameplay,
  type ResourceFlows,
} from './game/economy.js';
export {
  registerLogisticsGameplay,
  RoadGrid,
  PathService,
  HAULER_CAPACITY_WEIGHT,
  ROAD_COST_STONE,
  ROAD_SPEED,
  type LogisticsGameplay,
  type HaulerComponent,
} from './game/logistics.js';
export { HAULER_POOL_CAP } from './game/population.js';
export {
  registerSettlerGameplay,
  scoreSite,
  bestSiteNear,
  SETTLER_PARTY,
  SETTLER_CARRY,
  MIN_ADULTS_REMAINING,
  TIER2_REQUIREMENTS,
  type SettlerGameplay,
  type SettlerPartyComponent,
} from './game/settlers.js';
export { VILLAGE_RADIUS_T2 } from './game/villages.js';
export { INERT_MODIFIERS, type StatModifierView } from './game/economy.js';
export {
  registerKingdomGameplay,
  StatModifiers,
  KingdomLedger,
  STARTING_TREASURY,
  EDICT_CAP,
  ADVISOR_SALARY,
  TAX_RATES,
  OFFICES,
  type KingdomGameplay,
  type KingdomComponent,
  type CharacterComponent,
  type LedgerEntry,
  type Office,
} from './game/kingdom.js';
export {
  KnowledgeModel,
  hashKnowledge,
  type KnowledgeFact,
  type FactKind,
  type FactSource,
} from './ai/knowledge.js';
export { FogRegistry, fogQuery, type FogQuery } from './ai/fogQuery.js';
export {
  registerAiKernel,
  type AiGameplay,
  type AiKingdomInfo,
  type AiKernelOptions,
} from './ai/brain.js';
export { findBuildSite, type BuildSite } from './ai/placement.js';
export {
  detectNeeds,
  productionCapacity,
  housingCapacity,
  foodNeed,
  housingNeed,
  DEFAULT_NEED_EVALUATORS,
  type SettlementNeed,
  type NeedEvaluator,
  type NeedContext,
} from './ai/needs.js';
export {
  chooseBuildTarget,
  registerAiConstructionManager,
  type BuildIntent,
  type AiConstructionOptions,
} from './ai/manager.js';
export {
  registerAiMilitaryManager,
  pickRosterRecruit,
  planCastleRing,
  BARRACKS_DEF,
  RECRUIT_ORDER,
  RECRUIT_ROTATION,
  RECRUIT_BY_CLASS,
  AI_SIEGE_CAP,
  AI_SIEGE_MIN_UNITS,
  WAR_MIN_STRENGTH,
  WALL_DEF,
  CASTLE_RING_RADIUS,
  type AiWarTarget,
  type AiWarDiplomacy,
  type AiMilitaryOptions,
} from './ai/military.js';
export {
  computeConsiderations,
  planAwareNeeds,
  registerAiStrategicPlanner,
  defineAiPlanState,
  DEFAULT_PERSONALITY_WEIGHTS,
  DEFAULT_PLAN_ARCHETYPES,
  type PersonalityWeights,
  type Considerations,
  type PlanArchetype,
  type AiStrategicPlanner,
  type AiStrategicPlannerOptions,
  type AiDiplomacyContext,
  type AiMilitaryContext,
  type AiResearchContext,
} from './ai/planner.js';
export {
  registerMilitaryGameplay,
  MilitaryOps,
  type MilitaryGameplay,
  type MilitaryOptions,
  type UnitComponent,
  type ArmyComponent,
} from './game/military.js';
export {
  registerArmyGameplay,
  STANCES,
  SEASON_SPEED,
  SEASON_ATTRITION_MULT,
  SUPPLY_RANGE,
  ARMY_RATION_PER_HEAD,
  FATIGUE_RISE_PER_DAY,
  FATIGUE_RECOVER_PER_DAY,
  ATTRITION_RATE_AT_MAX_FATIGUE,
  type ArmyGameplay,
  type ArmyMovementComponent,
  type Stance,
} from './game/armies.js';
export {
  HierarchicalPathService,
  HPA_CHUNK,
  type HpaTerrain,
} from './nav/hpaStar.js';
export {
  registerSiegeGameplay,
  SiegeState,
  SIEGE_RANGE,
  BASE_BOMBARD_DAMAGE,
  SIEGE_BOMBARD_BONUS,
  ASSAULT_CASUALTY_MULTIPLIER,
  STARVATION_THRESHOLD,
  STARVATION_SURRENDER_DAYS,
  type SiegeGameplay,
  type CapitalFallHook,
} from './game/siege.js';
export {
  registerDefenceIntel,
  IntelState,
  estimateAssaultResistance,
  ESTIMATE_STRENGTH_PER_MAN,
  ESTIMATE_TOWER_RESISTANCE,
  ESTIMATE_WALL_RESISTANCE,
  ASSAULT_HOPELESS_FRACTION,
  type IntelGameplay,
  type IntelSnapshot,
  type IntelStructureRec,
} from './game/intel.js';
export {
  registerSuccessionGameplay,
  SuccessionState,
  CAPITULATION_WINDOW_DAYS,
  CAPITAL_FALLEN_EXHAUSTION_FLOOR,
  NEW_LORD_COOLDOWN_DAYS,
  NEW_LORD_SEARCH_RADIUS,
  type SuccessionGameplay,
  type SuccessionOptions,
} from './game/succession.js';
export {
  registerCastleGameplay,
  computeEnclosure,
  CASTLE_SEARCH_PADDING,
  type CastleGameplay,
  type DefenseGraph,
  type DefenseNode,
  type FortificationComponent,
} from './game/castles.js';
export {
  registerDefenceGameplay,
  KEEP_DEF,
  DEFENCE_KEEP_CENTRE,
  type DefenceGameplay,
  type DefenceMapState,
  type DefenceStructureComponent,
  type DefencePostComponent,
} from './game/defence.js';
export { registerAiDefenceManager, expandTemplate, DEFENCE_STONE_RESERVE, type AiDefenceOptions } from './ai/defence.js';
export {
  resolveSpatialAssault,
  publishAssaultResolved,
  ASSAULT_ORIGINS,
  DEFAULT_KEEP_HOLD_STRENGTH,
  ASSAULT_WALL_DAMAGE,
  TOWER_ATTACK,
  TOWER_RANGE,
  GARRISON_DEFENCE_BONUS,
  MAX_ASSAULT_ROUNDS,
  type AssaultOrigin,
  type AssaultResult,
  type AssaultTraceStep,
} from './game/assault.js';
export {
  DEFENCE_MAP_SIZE,
  DEFENCE_MAP_VERSION,
  DEFENCE_TILE,
  KEEP_CLEARING_RADIUS,
  defenceMapSeed,
  generateDefenceMap,
  digestDefenceMap,
  encodeDefenceMap,
  decodeDefenceMap,
  type DefenceTileCode,
} from './worldgen/defenceMap.js';
export {
  registerCombatGameplay,
  CombatState,
  ENGAGEMENT_RADIUS,
  SUBROUNDS_PER_TICK,
  MAX_ENGAGEMENT_TICKS,
  ROUT_MORALE_THRESHOLD,
  ROUT_CHANCE_PER_SUBROUND,
  BASE_MORALE_DAMAGE,
  CASUALTY_FRACTION_OF_DAMAGE,
  type CombatGameplay,
  type CombatOptions,
  type Engagement,
} from './game/combat.js';
export {
  registerDiplomacyGameplay,
  evaluateDeal,
  trustFactor,
  personalityMargin,
  napValue,
  pactValue,
  DiplomacyState,
  TRADE_VALUE,
  ACCEPT_THRESHOLD,
  GIFT_OPINION_PER_GOLD,
  MAX_GIFT_OPINION,
  GIFT_COOLDOWN_TICKS,
  INSULT_OPINION_DELTA,
  INSULT_COOLDOWN_TICKS,
  BREAK_PACT_OPINION_PENALTY,
  PACT_NAP,
  PACT_TRADE,
  evaluatePeaceDeal,
  WAR_DECLARED_OPINION_PENALTY,
  WAR_DECLARED_NO_CAUSE_PENALTY,
  WAR_EXHAUSTION_PER_DAY,
  FORCED_PEACE_EXHAUSTION,
  PEACE_BASE_VALUE,
  TRIBUTE_GOLD_TO_VALUE,
  type PactType,
  type DealEvaluation,
  type DiplomaticRelation,
  type DiplomacyOptions,
  type DiplomacyGameplay,
  type DiplomacyPersonality,
} from './game/diplomacy.js';
export {
  registerResearchGameplay,
  ResearchState,
  ERA_BREADTH_FRACTION,
  type ResearchGameplay,
  type ResearchGameplayOptions,
} from './game/research.js';
export { registerAiResearchManager, SCHOLAR_BUILDING_DEF, type AiResearchOptions } from './ai/research.js';
export {
  registerEventGameplay,
  evaluatePredicate,
  applyEffect,
  pacingMultiplier,
  EventState,
  BASE_DAILY_RATE,
  BASE_WEEKLY_RATE,
  PACING_TARGET_MIN,
  PACING_TARGET_MAX,
  SPECIAL_POOLS,
  DEFAULT_SPECIAL_EVENT_TUNING,
  type SpecialEventTuning,
  type EventContext,
  type EventEffectContext,
  type EventGameplay,
  type EventGameplayOptions,
  type EventDiplomacyHook,
  type EventResearchHook,
  type EventStateSave,
} from './game/events.js';
export { registerAiEventAnswering, type AiEventOptions } from './ai/events.js';
export {
  registerVictoryGameplay,
  DEFAULT_CONQUEST_SHARE,
  DEFAULT_HEGEMONY_YEARS,
  DEFAULT_PROSPERITY_HAPPINESS,
  DEFAULT_PROSPERITY_YEARS,
  DEFAULT_WONDER_COUNT,
  DEFAULT_YEAR_LIMIT,
  APPROACHING_FRACTION,
  type VictoryOptions,
  type VictoryDeps,
  type VictoryResult,
  type VictoryGameplay,
  type VictoryTrackProgress,
  type VictorySaveState,
} from './game/victory.js';
export {
  DIFFICULTY_LEVELS,
  DIFFICULTY_PRESETS,
  STORY_PRESET,
  FAIR_PRESET,
  HARD_PRESET,
  BRUTAL_PRESET,
  type DifficultyLevel,
  type DifficultyPreset,
} from './ai/difficulty.js';
export {
  composeMultiKingdom,
  flatTerrain,
  type MultiKingdomComposition,
  type MultiKingdomOptions,
} from './ai/multiKingdomHarness.js';
export {
  composeCampaign,
  contentPersonalityWeights,
  contentPersonalityAssigner,
  difficultyFromSettings,
  victoryFromSettings,
  DEFAULT_CAMPAIGN_STOCK,
  DEFAULT_CAMPAIGN_POPULATION,
  DEFAULT_CAMPAIGN_VICTORY,
  type ComposeCampaignOptions,
  type CampaignComposition,
} from './campaign.js';
