/**
 * Localization CLI (roadmap M44; doc 10 §6).
 *
 *   node packages/tools/dist/locale-tool.js pack   [--out FILE]
 *   node packages/tools/dist/locale-tool.js pseudo [--out-content FILE] [--out-app FILE]
 *
 * `pack` prints a translator pack (key/english/context, sorted) — everything
 * a translator needs, across both locale sources this codebase has (content
 * defs' en.json5 and the curated UI-chrome slice).
 *
 * `pseudo` regenerates the committed en-XA pseudo-locale files from the
 * current English source — run it whenever en.json5 or app/src/locale/en.ts
 * changes, the same "regenerate after editing the source" contract
 * gen-content.mjs already uses for embedded content.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { parseLocaleTable } from '@crowns/data';
import { EN_LOCALE } from '@crowns/app';
import { buildTranslatorPack } from './locale-extract.js';
import { buildEnXaTable } from './locale-pseudo.js';

const CONTENT_LOCALE_PATH = 'content/base/locale/en.json5';
const DEFAULT_OUT_CONTENT = 'content/base/locale/en-XA.json5';
const DEFAULT_OUT_APP = 'packages/app/src/locale/en-XA.ts';

const argValue = (flag: string): string | undefined => {
  const i = process.argv.indexOf(flag);
  return i === -1 ? undefined : process.argv[i + 1];
};

const contentEn = parseLocaleTable(CONTENT_LOCALE_PATH, readFileSync(CONTENT_LOCALE_PATH, 'utf8'));
const mode = process.argv[2] ?? 'pack';

if (mode === 'pack') {
  const pack = buildTranslatorPack([
    { context: 'content:event', table: contentEn },
    { context: 'app:ui-chrome', table: EN_LOCALE },
  ]);
  const json = JSON.stringify(pack, null, 2) + '\n';
  const out = argValue('--out');
  if (out !== undefined) {
    writeFileSync(out, json);
    console.log(`wrote ${pack.length} translator-pack entries to ${out}`);
  } else {
    process.stdout.write(json);
  }
} else if (mode === 'pseudo') {
  const outContent = argValue('--out-content') ?? DEFAULT_OUT_CONTENT;
  const outApp = argValue('--out-app') ?? DEFAULT_OUT_APP;
  const contentXa = buildEnXaTable(contentEn);
  const appXa = buildEnXaTable(EN_LOCALE);
  writeFileSync(
    outContent,
    '// AUTO-GENERATED by `node packages/tools/dist/locale-tool.js pseudo` — DO NOT EDIT.\n' +
      '// en-XA pseudo-locale (doc 10 §6): accented + ~30% expansion, for CI screenshot diffing.\n' +
      '// Source of truth: content/base/locale/en.json5. Regenerate after editing it.\n' +
      JSON.stringify(contentXa, null, 2) +
      '\n',
  );
  writeFileSync(
    outApp,
    '// AUTO-GENERATED by `node packages/tools/dist/locale-tool.js pseudo` — DO NOT EDIT.\n' +
      '// en-XA pseudo-locale (doc 10 §6). Source of truth: packages/app/src/locale/en.ts.\n' +
      "import type { LocaleTable } from '@crowns/core';\n\n" +
      `export const EN_XA_LOCALE: LocaleTable = ${JSON.stringify(appXa, null, 2)};\n`,
  );
  console.log(
    `wrote en-XA pseudo-locale: ${outContent} (${Object.keys(contentXa).length} keys), ${outApp} (${Object.keys(appXa).length} keys)`,
  );
} else {
  console.error(`unknown mode '${mode}' (use pack|pseudo)`);
  process.exitCode = 2;
}
