// Embeds content/ files into a generated TS module so the SAME parse+validate
// pipeline runs in Node, the sim worker, and the browser without a filesystem.
// The .json5 files remain the single source of truth; dev hot-reload replaces
// this embedding at M10 (mod loader watch mode, TDD §12).
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const readTree = (root) => {
  const files = {};
  const walk = (dir) => {
    for (const name of readdirSync(dir).sort()) {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) walk(p);
      else files[relative(root, p).replaceAll('\\', '/')] = readFileSync(p, 'utf8');
    }
  };
  walk(root);
  return files;
};
const files = readTree('content/base');
const examples = {};
try {
  for (const name of readdirSync('content/examples').sort()) {
    examples[name] = readTree(join('content/examples', name));
  }
} catch { /* no examples dir */ }

const out = `// AUTO-GENERATED by scripts/gen-content.mjs — DO NOT EDIT.
// Source of truth: content/**. Regenerate: npm run gen:content
export const BASE_CONTENT_FILES: Readonly<Record<string, string>> = ${JSON.stringify(files, null, 2)};

export const EXAMPLE_MOD_FILES: Readonly<Record<string, Readonly<Record<string, string>>>> = ${JSON.stringify(examples, null, 2)};
`;
writeFileSync('packages/data/src/generated/base-content.ts', out);
console.log(`gen-content: embedded ${Object.keys(files).length} base files + ${Object.keys(examples).length} example mod(s)`);
