// AUTO-GENERATED by `node packages/tools/dist/locale-tool.js pseudo` — DO NOT EDIT.
// en-XA pseudo-locale (doc 10 §6). Source of truth: packages/app/src/locale/en.ts.
import type { LocaleTable } from '@crowns/core';

export const EN_XA_LOCALE: LocaleTable = {
  "ui.village.upgrade-tier": "⟦Üpgrädë tïër ΞΞΞΞ⟧",
  "ui.kingdom.edict.repeal": "⟦Rëpëäl ΞΞ⟧",
  "ui.kingdom.edict.enact": "⟦Ënäct ΞΞ⟧",
  "ui.mods.apply": "⟦Äpply ΞΞ⟧",
  "ui.kingdom.ledger.heading": "⟦Lëdgër ΞΞ⟧",
  "ui.ledger.kind.tax": "⟦täx Ξ⟧",
  "ui.ledger.kind.edict-upkeep": "⟦ëdïct üpkëëp ΞΞΞΞ⟧",
  "ui.ledger.kind.advisor-salary": "⟦ädvïsör säläry ΞΞΞΞΞ⟧",
  "ui.ledger.kind.unit-recruit": "⟦ünït rëcrüïtëd ΞΞΞΞΞ⟧",
  "ui.ledger.kind.unit-upkeep": "⟦ünït üpkëëp ΞΞΞΞ⟧"
};
